# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataservice.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64\x61taservice.proto\"Z\n\x12\x44\x61taServiceRequest\x12\x0f\n\x07outlook\x18\x01 \x01(\t\x12\x12\n\ntemprature\x18\x02 \x01(\t\x12\x10\n\x08humidity\x18\x03 \x01(\t\x12\r\n\x05windy\x18\x04 \x01(\t\"$\n\x12\x44\x61taServiceRespond\x12\x0e\n\x06result\x18\x01 \x01(\x03\x32M\n\x0b\x44\x61taService\x12>\n\x12PredictPlayingGolf\x12\x13.DataServiceRequest\x1a\x13.DataServiceRespondb\x06proto3'
)




_DATASERVICEREQUEST = _descriptor.Descriptor(
  name='DataServiceRequest',
  full_name='DataServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='outlook', full_name='DataServiceRequest.outlook', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temprature', full_name='DataServiceRequest.temprature', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='DataServiceRequest.humidity', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='windy', full_name='DataServiceRequest.windy', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=111,
)


_DATASERVICERESPOND = _descriptor.Descriptor(
  name='DataServiceRespond',
  full_name='DataServiceRespond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='DataServiceRespond.result', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['DataServiceRequest'] = _DATASERVICEREQUEST
DESCRIPTOR.message_types_by_name['DataServiceRespond'] = _DATASERVICERESPOND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataServiceRequest = _reflection.GeneratedProtocolMessageType('DataServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATASERVICEREQUEST,
  '__module__' : 'dataservice_pb2'
  # @@protoc_insertion_point(class_scope:DataServiceRequest)
  })
_sym_db.RegisterMessage(DataServiceRequest)

DataServiceRespond = _reflection.GeneratedProtocolMessageType('DataServiceRespond', (_message.Message,), {
  'DESCRIPTOR' : _DATASERVICERESPOND,
  '__module__' : 'dataservice_pb2'
  # @@protoc_insertion_point(class_scope:DataServiceRespond)
  })
_sym_db.RegisterMessage(DataServiceRespond)



_DATASERVICE = _descriptor.ServiceDescriptor(
  name='DataService',
  full_name='DataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=151,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictPlayingGolf',
    full_name='DataService.PredictPlayingGolf',
    index=0,
    containing_service=None,
    input_type=_DATASERVICEREQUEST,
    output_type=_DATASERVICERESPOND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASERVICE)

DESCRIPTOR.services_by_name['DataService'] = _DATASERVICE

# @@protoc_insertion_point(module_scope)
